'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { listPacks, getPack } = require('./packs');

/**
 * Optional SwarmForge-style export (AH-E-50).
 * No runtime dependency on SwarmForge — generates conf + role prompt stubs.
 */

function loadPromptsMarkdown(promptsFile) {
  const text = fs.existsSync(promptsFile) ? fs.readFileSync(promptsFile, 'utf8') : '';
  const prompts = {};
  const re = /^##\s+(\w+)\s*\n([\s\S]*?)(?=^##\s+|\s*$)/gm;
  let match;
  while ((match = re.exec(text))) {
    prompts[match[1].toLowerCase()] = match[2].trim();
  }
  return prompts;
}

function renderSwarmforgeConf({ projectSlug = 'ariadne', packs = listPacks() } = {}) {
  const lines = [
    '# Generated by Ariadne · npm run swarm -- export-swarmforge',
    '# Optional: does NOT require SwarmForge installed to generate.',
    `# project: ${projectSlug}`,
    '',
    'version = 1',
    `project = "${projectSlug}"`,
    'runtime = "optional"',
    '',
  ];

  for (const pack of packs) {
    lines.push(`[[pack]]`);
    lines.push(`id = "${pack.id}"`);
    lines.push(`label = "${pack.label}"`);
    lines.push(`roles = [${pack.roles.map((role) => `"${role}"`).join(', ')}]`);
    lines.push(`model_hint = "${pack.modelHint || 'cheap'}"`);
    lines.push('');
  }

  lines.push('[bridge]');
  lines.push('queue_source = "ariadne-backlog"');
  lines.push('done_requires_evidence = true');
  lines.push('specifier_required_packs = ["four", "six"]');
  lines.push('qa_gate_packs = ["six"]');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function exportSwarmforgeBundle(outDir, options = {}) {
  const root = options.root || path.join(__dirname, '..');
  const promptsFile = options.promptsFile || path.join(root, 'docs', 'swarm', 'prompts.md');
  const prompts = loadPromptsMarkdown(promptsFile);
  const packs = options.packs || listPacks();
  const projectSlug = options.projectSlug || 'ariadne';

  fs.mkdirSync(outDir, { recursive: true });
  const confPath = path.join(outDir, 'swarmforge.conf');
  const conf = renderSwarmforgeConf({ projectSlug, packs });
  fs.writeFileSync(confPath, conf, 'utf8');

  const rolesDir = path.join(outDir, 'roles');
  fs.mkdirSync(rolesDir, { recursive: true });
  const roleIds = [...new Set(packs.flatMap((pack) => pack.roles))];
  const writtenRoles = [];
  for (const role of roleIds) {
    const body = prompts[role] || `(stub) Role ${role} — see docs/swarm/prompts.md`;
    const file = path.join(rolesDir, `${role}.prompt`);
    fs.writeFileSync(file, `${body}\n`, 'utf8');
    writtenRoles.push(path.relative(outDir, file));
  }

  const readme = path.join(outDir, 'README.md');
  const { renderBackendsMarkdown, governanceNote } = require('./backends');
  const gov = governanceNote();
  fs.writeFileSync(readme, `# SwarmForge export (optional)

Generated from Ariadne packs. **No SwarmForge runtime required** to produce this folder.

Use with SwarmForge only if you opt in; Ariadne nativo sigue siendo el camino por defecto.

- \`swarmforge.conf\` — packs + bridge hints
- \`roles/*.prompt\` — prompts alineados a docs/swarm/prompts.md
- Backends sugeridos: ver docs/swarm/backends.md (Ariadne dueño de Done)

Gobierno: \`${gov.completeCommand}\`

${renderBackendsMarkdown()}
Regenerate: \`npm run swarm -- export-swarmforge --out ${path.basename(outDir)}\`
`, 'utf8');

  return {
    outDir,
    confPath,
    files: [
      path.relative(outDir, confPath),
      'README.md',
      ...writtenRoles,
    ],
    packs: packs.map((pack) => pack.id),
    optionalRuntime: true,
  };
}

module.exports = {
  loadPromptsMarkdown,
  renderSwarmforgeConf,
  exportSwarmforgeBundle,
  getPack,
};
